### ISSUE TITLE
[BE] DB연동, OAuth2-Client lib 추가, Kakao Login REST API 구현

### ISSUE THREAD

**Issue by limjaein** [limjaein/LetsGetTogether#4]
- DB 연동
- OAuth2-Client lib 추가
 . application-oauth.yml 설정값 세팅
- Kakao Login REST API 구현
- 로그아웃 구현
- 화면 간 이동 시 사용자 정보 처리

**Comment by ky8778** [comment]
https://github.com/limjaein/LetsGetTogether/pull/8#discussion_r833962364

**Comment by ky8778** [comment]
[redirection 관련 커멘트](https://github.com/limjaein/LetsGetTogether/pull/8#discussion_r833965002)
